// SPDX-License-Identifier: AGPL-3.0-only
/**
 * GeneratedKnowledgeRepository — KnowledgeRepository over the generated JSON artifacts in
 * packages/knowledge/generated (built by scripts/build-knowledge-index.ts + build-evidence-index.ts).
 *
 * This is the production read model for build-time rendering: apps/web server components resolve
 * claims/evidence through it while prerendering, so no canonical YAML parsing and no SQLite
 * dependency enters the app. The generated directory is gitignored; a clean checkout must run
 * `pnpm build:knowledge` first, and the error below says exactly that instead of failing obscurely.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import type { ClaimEvidenceEntry, CompiledClaim, PublicSourceEntry, RouteEvidenceEntry, ToolEvidenceEntry } from "../src/compile.ts";
import type { ContentVersionRecord, GuidanceBlock, Locale, SourceRecord } from "../src/schemas/types.ts";
import type { ClaimId, GuidanceQuery, KnowledgeRepository, SourceId, SourceImpact } from "./types.ts";

/**
 * Locate packages/knowledge/generated by walking up from `startDir` (default: cwd — works from the
 * repo root and from apps/web, where Next.js runs). KNOWLEDGE_GENERATED_DIR overrides for tests/CI.
 */
export function findGeneratedDir(startDir: string = process.cwd()): string {
  const override = process.env.KNOWLEDGE_GENERATED_DIR;
  if (override) return resolve(override);
  let dir = resolve(startDir);
  for (;;) {
    const candidate = join(dir, "packages", "knowledge", "generated");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error("Could not locate packages/knowledge/generated from " + startDir);
}

interface ContentManifest {
  contentVersion: string;
  claims: CompiledClaim[];
  guidance: GuidanceBlock[];
  translations: Record<string, Record<string, string>>;
}

export class GeneratedKnowledgeRepository implements KnowledgeRepository {
  private readonly dir: string;
  private manifest: ContentManifest | undefined;
  private sources: SourceRecord[] | undefined;
  private claimEvidence: ClaimEvidenceEntry[] | undefined;
  private routeEvidence: RouteEvidenceEntry[] | undefined;
  private toolEvidence: ToolEvidenceEntry[] | undefined;
  private publicSources: PublicSourceEntry[] | undefined;
  private version: ContentVersionRecord | undefined;

  constructor(generatedDir: string = findGeneratedDir()) {
    this.dir = generatedDir;
  }

  private read<T>(name: string): T {
    const path = join(this.dir, name);
    if (!existsSync(path)) {
      throw new Error(
        `Generated knowledge artifact ${name} is missing under ${this.dir}. ` +
          "The derived read model is gitignored — run `pnpm build:knowledge` (or `pnpm build`) first.",
      );
    }
    return JSON.parse(readFileSync(path, "utf8")) as T;
  }

  private getManifest(): ContentManifest {
    this.manifest ??= this.read<ContentManifest>("content-manifest.json");
    return this.manifest;
  }

  async getClaim(id: ClaimId): Promise<CompiledClaim | null> {
    return this.getManifest().claims.find((c) => c.id === id) ?? null;
  }

  async getSource(id: SourceId): Promise<SourceRecord | null> {
    this.sources ??= this.read<{ sources: SourceRecord[] }>("source-manifest.json").sources;
    return this.sources.find((s) => s.id === id) ?? null;
  }

  async findGuidance(query: GuidanceQuery): Promise<GuidanceBlock[]> {
    return this.getManifest().guidance.filter(
      (block) =>
        (query.domain === undefined || block.domain === query.domain) &&
        (query.stage === undefined || block.stage === query.stage) &&
        (query.route === undefined || block.routes.includes(query.route)),
    );
  }

  async findClaimsBySource(sourceId: SourceId): Promise<CompiledClaim[]> {
    return this.getManifest().claims.filter((claim) => claim.sourceRefs.some((ref) => ref.sourceId === sourceId));
  }

  async getClaimEvidence(id: ClaimId): Promise<ClaimEvidenceEntry | null> {
    this.claimEvidence ??= this.read<ClaimEvidenceEntry[]>("claim-evidence-index.json");
    return this.claimEvidence.find((entry) => entry.claimId === id) ?? null;
  }

  async listClaimEvidence(): Promise<ClaimEvidenceEntry[]> {
    this.claimEvidence ??= this.read<ClaimEvidenceEntry[]>("claim-evidence-index.json");
    return this.claimEvidence;
  }

  async getRouteEvidence(route: string): Promise<RouteEvidenceEntry | null> {
    this.routeEvidence ??= this.read<RouteEvidenceEntry[]>("route-evidence-index.json");
    return this.routeEvidence.find((entry) => entry.route === route) ?? null;
  }

  async getSourceImpact(sourceId: SourceId): Promise<SourceImpact> {
    const claims = await this.findClaimsBySource(sourceId);
    const claimIds = claims.map((c) => c.id).sort();
    const claimIdSet = new Set(claimIds);
    this.routeEvidence ??= this.read<RouteEvidenceEntry[]>("route-evidence-index.json");
    this.toolEvidence ??= this.read<ToolEvidenceEntry[]>("tool-evidence-index.json");
    const routes = this.routeEvidence.filter((entry) => entry.claimIds.some((id) => claimIdSet.has(id))).map((entry) => entry.route).sort();
    const toolIds = this.toolEvidence.filter((entry) => entry.claimIds.some((id) => claimIdSet.has(id))).map((entry) => entry.toolId).sort();
    return { sourceId, claimIds, routes, toolIds };
  }

  async listPublicSources(): Promise<PublicSourceEntry[]> {
    this.publicSources ??= this.read<PublicSourceEntry[]>("source-public-index.json");
    return this.publicSources;
  }

  async getText(locale: Locale, key: string): Promise<string | null> {
    return this.getManifest().translations[locale]?.[key] ?? null;
  }

  async getContentVersion(): Promise<ContentVersionRecord> {
    this.version ??= this.read<ContentVersionRecord>("content-version.json");
    return this.version;
  }
}
